name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '6.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Test with dotnet
        run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
            name: dotnet-results-${{ matrix.dotnet-version }}
            path: TestResults-${{ matrix.dotnet-version }}
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Gera tag docker
      run: echo "DOCKER_IMAGE=ellyson100/poc-api" >> $GITHUB_ENV
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build/Push Imagem Docker
      run: |
        echo "${{ secrets.SENHA_HUB }}" | docker login -u ellyson100 --password-stdin
        docker build -t $DOCKER_IMAGE:$GITHUB_RUN_NUMBER -f POC.API/Dockerfile POC.API
        docker push $DOCKER_IMAGE:$GITHUB_RUN_NUMBER
      
    - name: Instala Kustomize
      run: sudo snap install kustomize

    - name: Atualiza Imagem Kustomize
      run: |
        git clone https://github.com/ellyson100/POC_kustomize.git && cd POC_kustomize
        cd overlays && kustomize edit set image $DOCKER_IMAGE=$DOCKER_IMAGE:$GITHUB_RUN_NUMBER && cd ..
        git config user.email "ellyson100@gmail.com"
        git config user.name "ellyson100"
        git add . && git commit -m "Atualiza kustomize - Build $GITHUB_RUN_NUMBER"
        git push https://${{ secrets.TOKEN }}@github.com/ellyson100/POC_kustomize.git
