name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Gera tag docker
      run: echo "DOCKER_IMAGE=ellyson100/poc-api" >> $GITHUB_ENV
        
    #- name: Checkout code
     # uses: actions/checkout@v2
      
    #- name: Login
     # run: echo "${{ secrets.SENHA_HUB }}" | docker login -u ellyson100 --password-stdin

    #- name: Build
     # run: docker build -t $DOCKER_IMAGE:$GITHUB_RUN_NUMBER -f POC.API/Dockerfile POC.API

    #- name: Push
     # run: docker push $DOCKER_IMAGE:$GITHUB_RUN_NUMBER
      
    - name: Instala Kustomize
      run: sudo snap install kustomize

    - name: Atualiza Imagem Kustomize
      run: |
        git clone https://github.com/ellyson100/POC_kustomize.git && cd POC_kustomize
        cd overlays && kustomize edit set image $DOCKER_IMAGE=$DOCKER_IMAGE:$GITHUB_RUN_NUMBER && cd ..
        git add . && git commit -m "Atualiza kustomize - Build $GITHUB_RUN_NUMBER"
        git push https://${{ secrets.TOKEN }}@github.com/ellyson100/POC_kustomize.git
