name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login
      run: echo "${{ secrets.SENHA_HUB }}" | docker login -u ellyson100 --password-stdin

    - name: Build
      run: cd POC.API && docker build -t ellyson100/poc-api:$GITHUB_RUN_NUMBER .

    - name: Push
      run: docker push ellyson100/poc-api:$GITHUB_RUN_NUMBER
